### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ovr** [phalcon/zephir#710]
Code to reproduce
https://github.com/lynx/benchmark/blob/master/benchmark.php#L51
This bugged only in cycle, for third  iteration 0, 1, 2 (fault)

https://github.com/lynx/lynx/blob/master/ext/lynx/orm/modelsmanager.zep.c#L78
Bugged when observer class name var

I was trying to find it, but cannot
Maybe this bug caused in fcall

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000006b2b7a in ?? ()
(gdb) bt full
#0  0x00000000006b2b7a in ?? ()
No symbol table info available.
#1  0x00007fffef2c1ad6 in zephir_memory_alloc (var=var@entry=0x7fffffffa640) at /root/build/lynx/ext/kernel/memory.c:588
No locals.
#2  0x00007fffef2e79ad in zim_Lynx_ORM_ModelsManager_get (ht=<optimized out>, return_value=0x7ffff7e1d8b0, return_value_ptr=0x7fffffffab38, this_ptr=0x7ffff7fdf670, return_value_used=<optimized out>) at /root/build/lynx/ext/lynx/orm/modelsmanager.zep.c:100
        ZEPHIR_LAST_CALL_STATUS = <optimized out>
        classname_param = 0x7ffff7e1d8b0
        cacheDriver = 0x0
        _2 = 0x0
        _4 = 0x7fff00000001
        _5 = 0x0
        _6 = 0x7ffff7ea6058
        classname = 0x7ffff7e1f298
#3  0x00000000006c9bbb in dtrace_execute_internal ()
No symbol table info available.
#4  0x00000000006cb8b5 in zend_call_function ()
No symbol table info available.
#5  0x00007fffef2cf56a in zephir_call_user_function (object_pp=0x7fffffffa9e8, obj_ce=<optimized out>, obj_ce@entry=0x10ec080, type=type@entry=zephir_fcall_method, function_name=0x7ffff7e1e5b8, retval_ptr_ptr=retval_ptr_ptr@entry=0x7fffffffab38, 
    cache_entry=cache_entry@entry=0x0, param_count=param_count@entry=1, params=params@entry=0x7fffffffac00) at /root/build/lynx/ext/kernel/fcall.c:459
        params_ptr = 0x7fffffffa920
        params_array = 0x0
        static_params_array = {0x7fffffffac00, 0x0, 0x7fffffffa998, 0x6e7c28 <_zend_hash_index_update_or_next_insert+120>, 0x7fff00000008, 0x4f7e1f0e0, 0x0, 0x7fffffffab38, 0x7ffff7e1d978, 0x4}
        local_retval_ptr = 0x0
        status = <optimized out>
        fci = {size = 72, function_table = 0x10ec0a8, function_name = 0x7ffff7e1e5b8, symbol_table = 0x0, retval_ptr_ptr = 0x7fffffffab38, param_count = 1, params = 0x7fffffffa920, object_ptr = 0x7ffff7fdf670, no_separation = 1 '\001'}
        fcic = {initialized = 1 '\001', function_handler = 0x10ec4c0, calling_scope = 0x10ec080, called_scope = 0x10ec080, object_ptr = 0x7ffff7fdf670}
        fcall_key = 0x7ffff7fddcd0 "get"
        fcall_key_len = 20
        fcall_key_hash = 4524325197468627267
        temp_cache_entry = 0x1181c28
        old_scope = 0x0
```
If i disable function call 

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000006d99b4 in _zval_copy_ctor_func ()
(gdb) bt full
#0  0x00000000006d99b4 in _zval_copy_ctor_func ()
No symbol table info available.
#1  0x00000000006cb094 in zend_call_function ()
No symbol table info available.
#2  0x00007fffef2cf56a in zephir_call_user_function (object_pp=0x7fffffffa9e8, obj_ce=<optimized out>, obj_ce@entry=0x10ec080, type=type@entry=zephir_fcall_method, function_name=0x7ffff7e1dcd0, retval_ptr_ptr=retval_ptr_ptr@entry=0x7fffffffab38, 
    cache_entry=cache_entry@entry=0x0, param_count=param_count@entry=1, params=params@entry=0x7fffffffac00) at /root/build/lynx/ext/kernel/fcall.c:459
        params_ptr = 0x7fffffffa920
        params_array = 0x0
        static_params_array = {0x7fffffffac00, 0x0, 0x7fffffffa998, 0x6e7c28 <_zend_hash_index_update_or_next_insert+120>, 0x7fff00000008, 0x4f7e1efe8, 0x0, 0x7fffffffab38, 0x7ffff7e1d978, 0x4}
        local_retval_ptr = 0x0
        status = <optimized out>
        fci = {size = 72, function_table = 0x10ec0a8, function_name = 0x7ffff7e1dcd0, symbol_table = 0x0, retval_ptr_ptr = 0x7fffffffab38, param_count = 1, params = 0x7fffffffa920, object_ptr = 0x7ffff7fdf670, no_separation = 1 '\001'}
        fcic = {initialized = 1 '\001', function_handler = 0x10ec4c0, calling_scope = 0x10ec080, called_scope = 0x10ec080, object_ptr = 0x7ffff7fdf670}
        fcall_key = 0x0
        fcall_key_len = 7864819
        fcall_key_hash = 140737488333624
        temp_cache_entry = 0x0
        old_scope = 0x0
#3  0x00007fffef2cfb9b in zephir_call_class_method_aparams (return_value_ptr=return_value_ptr@entry=0x7fffffffab38, ce=0x10ec080, type=type@entry=zephir_fcall_method, object=object@entry=0x7ffff7fdf670, method_name=method_name@entry=0x7fffef2fc57c "get", 
    method_len=method_len@entry=3, cache_entry=cache_entry@entry=0x0, param_count=param_count@entry=1, params=params@entry=0x7fffffffac00) at /root/build/lynx/ext/kernel/fcall.c:676
        possible_method = <optimized out>
        rv = 0x0
        rvp = <optimized out>
        fn = 0x7ffff7e1dcd0
        mn = <optimized out>
        status = <optimized out>
        __FUNCTION__ = "zephir_call_class_method_aparams"
#4  0x00007fffef2f0929 in zim_Lynx_ORM_UnitOfWork_commit (ht=<optimized out>, return_value=<optimized out>, return_value_ptr=<optimized out>, this_ptr=0x7ffff7fdf5e0, return_value_used=<optimized out>) at /root/build/lynx/ext/lynx/orm/unitofwork.zep.c:208
        params_ = {0x7ffff7e1d8b0}
        _13 = <optimized out>
        _8 = 0x0
        _12 = 0x0
        _17 = 0x0
        _29 = 0x0
        ZEPHIR_LAST_CALL_STATUS = <optimized out>
        _2 = 0x7ffff7fdf840
        _10 = 0x7ffff7e204e0
        _27 = 0x1
        _31 = 0x10f5810
        _1 = 0x7ffff7fdcbd8
        _9 = 0x0
        _26 = 0x6
        _30 = 0x7ffff7ee0590
        entity = 0x7ffff7fd98b8
        model = 0x7ffff7fdc960
        modelInfo = 0x0
        result = 0x7ffff7e1e288
        primaryField = 0x7ffff7e1e238
        _3 = <optimized out>
        lastInsertId = 0x7ffff7e20390
        extractValues = 0x7ffff7e1e470
        insertValues = 0x7ffff7e1d8b0
        property = 0x7ffff7e1df58
        value = 0x7ffff7fde6d8
        key = 0x7ffff7e1dbf8
        types = 0x7ffff7e1d328
        _4 = 0x7ffff7e1d750
        _5 = <optimized out>
        _6 = 0x7ffff7fdf670
        _7 = 0x7ffff7e1d8b0
        _11 = <optimized out>
        _14 = 0x7ffff7e219d8
        _15 = 0x7ffff7e1df28
        _16 = 0x7ffff7fdff60
.....
```

```sh
oot@benchmark:~/build/lynx# gcc -v
Target: x86_64-linux-gnu
Thread model: posix
gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) 

Ubuntu
Latest Zephir
```

You can test it by

```sh
git clone https://github.com/lynx/benchmark.git
cd benchmark
vagrant up
vagrant ssh
cd /var/www/benchmark/
php benchmark.php
```

**Comment by ovr** [comment]
cc @andresgutierrez

**Comment by steffengy** [comment]
@ovr
Is that fixed?
When I tried ```php benchmark.php``` it just created the records, without crashing.
