### ISSUE TITLE
PHP Zephir\ParseException:  Syntax error in /work/zephir/test/fasta.zep on line 12

### ISSUE THREAD

**Issue by valVk** [phalcon/zephir#880]
hi
latest commit is 

```
commit 63b0d1ec7236a8f0987d8c732a641a6103a59c0e
Merge: e6f94e7 102f796
Author: Andres Gutierrez <gutierrezandresfelipe@gmail.com>
Date:   Tue Apr 7 01:43:03 2015 -0500

    Merge pull request #877 from phalcon/mcall-cache-analysis
    
    Better method cache analysis

commit 102f79617ac0fa60865db3611590cae76cf7ecd4
Author: Andres Gutierrez <gutierrezandresfelipe@gmail.com>
Date:   Tue Apr 7 01:34:17 2015 -0500

    Better Method cache analysis

commit e6f94e72e75029da022c9293b4e6a64d687c1468
Author: Andres Gutierrez <gutierrezandresfelipe@gmail.com>
Date:   Mon Apr 6 21:44:07 2015 -0500
```

the error looks like listed below

```
./bin/zephir compile                                                                                  [16:08:33]
PHP Zephir\ParseException:  Syntax error in /work/zephir/test/fasta.zep on line 12 in /work/zephir/Library/CompilerFile.php on line 525
PHP Stack trace:
PHP   1. {main}() /work/zephir/compiler.php:0
PHP   2. Zephir\Bootstrap::boot() /work/zephir/compiler.php:21
PHP   3. Zephir\Commands\CommandAbstract->execute() /work/zephir/Library/Bootstrap.php:200
PHP   4. Zephir\Compiler->compile() /work/zephir/Library/Commands/CommandAbstract.php:71
PHP   5. Zephir\Compiler->generate() /work/zephir/Library/Compiler.php:893
PHP   6. Zephir\Compiler->recursivePreCompile() /work/zephir/Library/Compiler.php:730
PHP   7. Zephir\Compiler->preCompile() /work/zephir/Library/Compiler.php:214
PHP   8. Zephir\CompilerFile->preCompile() /work/zephir/Library/Compiler.php:175
Zephir\ParseException: Syntax error in /work/zephir/test/fasta.zep on line 12

	   str   = join(seq, new array(len * 60 + 1)),
	-----------------------------^

at Library/CompilerFile.php(525)
#0 Library/Compiler.php(175): Zephir\CompilerFile->preCompile(Object(Zephir\Compiler))
#1 Library/Compiler.php(214): Zephir\Compiler->preCompile('test/fasta.zep')
#2 Library/Compiler.php(730): Zephir\Compiler->recursivePreCompile('test')
#3 Library/Compiler.php(893): Zephir\Compiler->generate(Object(Zephir\Commands\CommandCompile))
#4 Library/Commands/CommandAbstract.php(71): Zephir\Compiler->compile(Object(Zephir\Commands\CommandCompile))
#5 Library/Bootstrap.php(200): Zephir\Commands\CommandAbstract->execute(Object(Zephir\Config), Object(Zephir\Logger))
#6 compiler.php(21): Zephir\Bootstrap::boot()
#7 {main}

```

**Comment by andresgutierrez** [comment]
Your parser needs to be recompiled:

```bash
./install
```

**Comment by valVk** [comment]
Thanks.
