### ISSUE TITLE
method_exist on self

### ISSUE THREAD

**Issue by fezfez** [phalcon/zephir#999]
Hi,

I have this error when i try to compile this code : 

```
Zephir\CompilerException: Cannot read variable 'self' because it wasn't declared in .../tmp/Tmp.zep on line 12

	                method_exists(self, foo);
	----------------------------------^

at Library/SymbolTable.php(207)
#0 Library/Call.php(617): Zephir\SymbolTable->getVariableForRead('self', Object(Zephir\CompilationContext), Array)
#1 Library/Optimizers/FunctionCall/MethodExistsOptimizer.php(59): Zephir\Call->getReadOnlyResolvedParams(Array, Object(Zephir\CompilationContext), Array)
#2 Library/FunctionCall.php(233): Zephir\Optimizers\FunctionCall\MethodExistsOptimizer->optimize(Array, Object(Zephir\FunctionCall), Object(Zephir\CompilationContext))
#3 Library/FunctionCall.php(309): Zephir\FunctionCall->optimize('method_exists', Array, Object(Zephir\FunctionCall), Object(Zephir\CompilationContext))
#4 Library/FunctionCall.php(600): Zephir\FunctionCall->_callNormal(Array, Object(Zephir\CompilationContext))
#5 Library/StatementsBlock.php(271): Zephir\FunctionCall->compile(Object(Zephir\Expression), Object(Zephir\CompilationContext))
#6 Library/ClassMethod.php(1687): Zephir\StatementsBlock->compile(Object(Zephir\CompilationContext), false, 0)
#7 Library/ClassDefinition.php(1126): Zephir\ClassMethod->compile(Object(Zephir\CompilationContext))
#8 Library/CompilerFile.php(203): Zephir\ClassDefinition->compile(Object(Zephir\CompilationContext))
#9 Library/CompilerFile.php(845): Zephir\CompilerFile->compileClass(Object(Zephir\CompilationContext), 'Tmp', Array)
#10 Library/Compiler.php(817): Zephir\CompilerFile->compile(Object(Zephir\Compiler), Object(Zephir\StringsManager))
#11 Library/Commands/CommandAbstract.php(92): Zephir\Compiler->generate(Object(Zephir\Commands\CommandGenerate))
#12 Library/Bootstrap.php(200): Zephir\Commands\CommandAbstract->execute(Object(Zephir\Config), Object(Zephir\Logger))
#13 compiler.php(21): Zephir\Bootstrap::boot()
#14 {main}
```

```zephir
namespace Tmp;

class Tmp
{
        public static function isOkStatic()
        {
                var foo;

                let foo = "isOk";

                method_exists(self, foo);

        }
}
```

Zephir version : 8c9f4c434a3f293d19fc0b053db79a41987ae821
Linux version 3.5.0-51-generic (buildd@toyol) (gcc version 4.7.2 (Ubuntu/Linaro 4.7.2-2ubuntu1) ) #76-Ubuntu SMP Thu May 15 21:19:10 UTC 2014

**Comment by steffengy** [comment]
PHP also does not support something like that.
Maybe try something like:
1) `` method_exists(__CLASS__, foo); ``
2) `` method_exists(get_class(), foo); ``
3) ``method_exists(get_called_class(), foo);`` (static::)

**Comment by andresgutierrez** [comment]
```php
<?php

class Math
{
        function check()
        {
                return method_exists(self, "fibo");
        }
}


$n = new Math();
var_dump($n->check())

```
PHP Notice:  Use of undefined constant self - assumed 'self' in /Users/andres/zephir/a.php on line 7
```

**Comment by fezfez** [comment]
Sorry for the mistake... i thought that was possible.

Close
